### ISSUE TITLE
Parametro errado no FDPhysPGDriverLink1

### ISSUE THREAD

**Issue by JFSF** [armandocorrea/workshop-academiadocodigo-angular-delphi#1]
Nos parâmetros deste componente o "VendorLib" está setado para "C:\Program Files (x86)\PostgreSQL\10\bin\libpq.dll" o que origina que quando o executável do configurador for executado vai procurar uma dll numa path que pode não corresponder à do utilizador.

Este parâmetro deverá ser setado em tempo de runtime através do próprio configurador.

![image](https://github.com/armandocorrea/workshop-academiadocodigo-angular-delphi/assets/1583154/943da0f6-519b-44f3-8f63-ddd4ef26ac19)

**Comment by armandocorrea** [comment]
![Captura de tela 2024-02-13 141813](https://github.com/armandocorrea/workshop-academiadocodigo-angular-delphi/assets/41443587/658e8881-ca4a-40dd-98fa-120f260debfe)

Criado campo para adicionar o path do VendorLib.

Obrigado pela contribuição.

Obs.: Lembrando que apenas está homologado para o PostgreSQL.
Para usar outros tipos de banco devemos ajustar o FDPHYS.
